#!/bin/sh
#
# conkyrc file for dzen
###

background no
out_to_console yes
out_to_x no
override_utf8_locale yes
update_interval 1
total_run_times 0
GDBAR=gdbar

TEXT
^i(.share/icons/dzen/drive-harddisk-2_16x16.xpm) ${hddtemp /dev/sda} \
^i(.share/icons/dzen/ac.xbm) ${hddtemp /dev/sda} \
^i(.share/icons/dzen/ac.xbm) ${hddtemp /dev/sda} \
