#!/bin/sh
#
# conkyrc file for dzen
###

background no
out_to_console yes
out_to_x no
override_utf8_locale yes
update_interval 1
total_run_times 0

TEXT
^fg(grey60) ${mpd_status} \
^fg(orange)[^fg(grey90)$(top name 1}^fg(orange)/^fg(grey90)${top cpu 1}^fg(orange)]\
[^fg(grey90)${top name 2}^fg(orange)/^fg(grey90)${top cpu 2}^fg(orange)]
