#!/bin/sh
#
# conkyrc file for dzen
###

background no
out_to_console yes
out_to_x no
override_utf8_locale yes
update_interval 1
total_run_times 0

TEXT
^fg(grey90)/: ^fg(orange)[^fg(grey90)${fs_bar 1,7 /}^fg(orange)] ^fg(grey90)${fs_free_perc /} % \
^fg(grey90)/home: ^fg(orange)[^fg(grey90)${fs_bar 1,7 /home}^fg(orange)] ^fg(grey90)${fs_free_perc /home} % \
^fg(grey90)/wdc2tb: ^fg(orange)[^fg(grey90)${fs_bar 1,7 /mnt/wdc2tb}^fg(orange)] ^fg(grey90)${fs_free_perc /mnt/wdc2tb} % \
^fg(grey90)/wdc1tb: ^fg(orange)[^fg(grey90)${fs_bar 1,7 /mnt/wdc1tb}^fg(orange)] ^fg(grey90)${fs_free_perc /mnt/wdc1tb} % \
