#!/bin/sh
#
# conkyrc file for dzen with mpd server info
###
mpd_host /run/mpd/socket
background no
out_to_console yes
out_to_x no
override_utf8_locale yes
update_interval 1
total_run_times 0

TEXT
${if_mpd_playing}
 ^p(4)^fg(khaki) ^i(/home/lasseb/.share/icons/dzen/phones.xbm)\
 ^fg(grey90)[ ^ca(1, mpc toggle)${mpd_status}^ca()${if_mpd_playing} - ${mpd_elapsed}/${mpd_length}$endif ]\
 ^fg(lightblue)^ca(1, mpc prev)^ca(3, mpc next)^ca(4, mpc seek +5)^ca(5, mpc seek -5)${mpd_artist}^fg(orange) -\
 ^fg(lightgreen)${mpd_title}^fg(orange) - ^fg(darkcyan)${mpd_album}^fg()^ca()^ca()^ca()^ca()\
${else}\
 ^p(4)^fg(orange) ^i(/home/lasseb/.share/icons/dzen/phones.xbm)^fg() Mpd Offline\
${endif}
