fpath=($HOME/.zsh/functions $fpath)

# colors
eval `dircolors $HOME/.zsh/colors`

autoload -U zutil
autoload -U compinit
autoload -U complist
zstyle ':completion::complete:*' use-cache 1

# mad I know, prefering emacs bindings when I'm a vim user!
bindkey -e
bindkey '^K' kill-whole-line
bindkey "\e[H" beginning-of-line        # Home (xorg)
bindkey "\e[1~" beginning-of-line       # Home (console)
bindkey "\e[4~" end-of-line             # End (console)
bindkey "\e[F" end-of-line              # End (xorg)
#bindkey "\e[2~" overwrite-mode          # Ins
bindkey "\e[2~" quoted-insert           # Ins
bindkey "\e[3~" delete-char             # Delete
bindkey "\e[5~" beginning-of-history    # PageUp
bindkey "\e[6~" end-of-history          # PageDown

compinit

setopt promptsubst
setopt CORRECT
setopt ALWAYS_TO_END
setopt NOTIFY
setopt NOBEEP
setopt AUTOLIST
setopt AUTOCD
setopt PRINT_EIGHT_BIT
setopt NONOMATCH
setopt PRINT_EXIT_VALUE

#Load the prompt theme system
autoload -U promptinit
promptinit

# Use the wunjo prompt theme
prompt wunjo

# Resource files
for file in $HOME/.zsh/rc/*.rc; do
    source $file
done

